import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import CinemaBackground from "@/components/forms/CInemaBG";
import AppProviders from "@/components/AppProviders";
import { getServerLang } from "@/lib/i18n/server";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Cinema",
  description: "Generated by create next app",
};

// ✅ phải async để await getServerLang()
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const lang = await getServerLang();

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}>
        <CinemaBackground />
        <div className="relative z-10 min-h-screen">
          <AppProviders initialLang={lang}>{children}</AppProviders>
        </div>
      </body>
    </html>
  );
}
