import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientProvider from "@/components/forms/ClientProvider";
import CinemaBackground from "@/components/forms/CInemaBG";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        {/* ✅ Background toàn app */}
        <CinemaBackground />

        {/* ✅ Nội dung app nằm trên background */}
        <div className="relative z-10">
          <ClientProvider>{children}</ClientProvider>
        </div>
      </body>
    </html>
  );
}
